name: 'Add relevant labels to PR'
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # remove_label:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-ecosystem/action-remove-labels@v1
  #       with:
  #         github_token: '${{ secrets.BREWBOT_GITHUB_TOKEN }}'
  #         labels: |
  #           Tested ✓
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.BREWBOT_GITHUB_TOKEN }}'
          configuration-path: .github/config/pr-labeller.yml
          sync-labels: ''