name: pull-request

on:
  pull_request:
    types: ['opened', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Generate Short SHA
        id: build_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.BREWBOT_GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_push
        with:
          context: .
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          push: true
          tags: ghcr.io/overtheairbrew/brewing-platform:pr-${{github.event.pull_request.number}}
      - name: Comment docker image link on pr
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Docker image related to this pr: [ghcr.io/overtheairbrew/brewing-platform:pr-${{github.event.pull_request.number}}](https://github.com/OverTheAirBrew/brewing-platform/pkgs/container/brewing-platform?tag=${{github.event.pull_request.number}})
          pr_number: ${{github.event.pull_request.number}}
          comment_tag: pr-docker-info