name: pull-request

on:
  pull_request:
    types: ['opened', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Generate Short SHA
        id: build_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Docker Package
        run: docker build -t overtheairbrew/brewing-platform:${{ steps.build_sha.outputs.sha_short }} .